redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/paperclip/astra-business-sites"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/holdquarter/*"
to = "/holdquarter/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/thesights/*"
to = "/thesights/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/astrawatch/*"
to = "/astrawatch/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sitemap-holdquarter.xml"
to = "/holdquarter/sitemap-holdquarter.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sitemap-thesights.xml"
to = "/thesights/sitemap-thesights.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sitemap-astrawatch.xml"
to = "/astrawatch/sitemap-astrawatch.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]